#%RAML 1.0 NamedExample

value:
  GetCitiesByCountryResponse: 
    __text: <![CDATA[&lt;NewDataSet&gt;\n  &lt;Table&gt;\n    &lt;Country&gt;Australia&lt;/Country&gt;\n &lt;City&gt;Archerfield Aerodrome&lt;/City&gt;\n  &lt;/Table&gt;\n  \n&lt;/NewDataSet&gt;]]>\n