#%RAML 1.0 NamedExample

value:
  GetWeatherResponse: 
    __text: <![CDATA[&lt;NewDataSet&gt;\n &lt;Location&gt;Melbourne&lt;/Location&gt;\n &lt;Time&gt;11 AM&lt;/Time&gt;\n &lt;Wind&gt;15 km per hour&lt;/Wind&gt;\n &lt;Visibility&gt;10 km&lt;/Visibility&gt;\n &lt;SkyConditions&gt;sunny&lt;/SkyConditions&gt;\n &lt;Temperature&gt;18&lt;/Temperature&gt;\n &lt;DewPoint&gt;2 C&lt;/DewPoint&gt;\n &lt;RelativeHumidity&gt;35&lt;/RelativeHumidity&gt;\n &lt;Status&gt;Normal&lt;/Status&gt;\n&lt;/NewDataSet&gt;]]>\n